[package]
name = "wgpu-game-engine"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
winit = { version = "0.29", features = ["rwh_05"] }
env_logger = "0.11.7"
log = "0.4"
wgpu = "24.0"
pollster = "0.4.0"
bytemuck = { version = "1.16", features = ["derive"] }